### ISSUE TITLE
Links are none obvious - maybe we should look at the styles in use

### ISSUE THREAD

**Issue by computamike** [CCHits/Website#104]
I was looking at the front page, and I noticed that some of the hyperlinks look the same as normal text..
![image](https://user-images.githubusercontent.com/464876/46315851-714f0280-c5c6-11e8-8c75-0a88f6dbc496.png)

**Comment by ymauray** [comment]
I'm doing CSS stuff for some other issues. I'll fix this one too.

**Comment by JonTheNiceGuy** [comment]
If the committed fix isn't right for you @computamike, reopen this :)

**Comment by computamike** [comment]
@JonTheNiceGuy looks better I think.
