### ISSUE TITLE
Publicise short codes

### ISSUE THREAD

**Issue by JonTheNiceGuy** [CCHits/Website#3]
This content was written on code.cchits.net. Some of these short codes have been implemented - notably the /t/ and /s/ codes, although the /d/, /w/ and /m/ may also have been done.

This should be publicised on the site.

<hr />

To help reduce URL lengths for social media sites, the following short codes could be used:

 http://baseurl/show/INT => http://baseurl/s/INT (0-9)
 http://baseurl/show/INT => http://baseurl/s/xALPHANUM Note the x prefix to indicate the smaller code (0-9A-Za-z)
 http://baseurl/track/INT => http://baseurl/t/INT (0-9)
 http://baseurl/track/INT => http://baseurl/t/xALPHANUM Note the x prefix to indicate the smaller code (0-9A-Za-z)
 http://baseurl/daily/YYYYMMDD => http://baseurl/d/YYMMDD
 http://baseurl/weekly/YYYYMMDD => http://baseurl/w/YYMMDD
 http://baseurl/monthly/YYYYMMDD => http://baseurl/m/YYMMDD

(User:JonTheNiceGuy - 2011-04-14)

**Comment by ymauray** [comment]
What is the "xALPHANUM" option supposed to represent ?

**Comment by thelovebug** [comment]
@ymauray I believe this represents the literal value 'x' followed by the showId/trackId in hexadecimal form.

**Comment by thelovebug** [comment]
I might suggest that we factor in the whole "publicising" piece when the individual show/track pages are revamped as part of #2.

**Comment by ymauray** [comment]
Do we really have a use case for that hexadecimal value ?

**Comment by thelovebug** [comment]
It saves a couple of bytes in the URL length.  This one is for @JonTheNiceGuy to decide, I think.

**Comment by JonTheNiceGuy** [comment]
The xALPHANUM is actually base 62 (26 A-Z, 26 a-z, 10 0-9) but was created when Twitter was deducting characters from URLs. Not relevant now.
