### ISSUE TITLE
Re-implement CCHITS coding standard

### ISSUE THREAD

**Issue by ymauray** [CCHits/Website#59]
The `.phpcs` directory contains the definition of CCHits' coding standard. Unfortunately, they are out of date.
Re-implementing that against the latest version of `PHP Code Sniffer` would then allow for a local pre-commit git hook to be run. That hook would refuse to commit any code that doesn't comply with our coding standard.

**Comment by ymauray** [comment]
Fixed in #60

**Comment by JonTheNiceGuy** [comment]
Worth hooking it up to TravisCI? https://docs.travis-ci.com/user/languages/php/#Installing-PEAR-packages

**Comment by ymauray** [comment]
I would have two arguments agains that :
1. If all commits contain only standard compliant source files, then there is no need for re-checking at the CI level
2. Until every source file is compliant, the CI will complain, and it's going to be very annoying :-)

Other than that, it could be nice to have that in place in case non compliant code slips through a commit.

**Comment by JonTheNiceGuy** [comment]
Confirmed!
