### ISSUE TITLE
The vote adjustment link on the track page is incorrect

### ISSUE THREAD

**Issue by thelovebug** [CCHits/Website#90]
On the [track](https://cchits.net/track/1) page, the vote adjustment link points to [/about#voteadj](https://cchits.net/about#voteadj), but the anchor on the [/about](https://cchits.net/about) page is [/about#voteadjust](https://cchits.net/about#voteadjust).

Either:

1.  the [/track](https://cchits.net/track/1) page needs the link changing to [/about#voteadjust](https://cchits.net/about#voteadjust), or
2. the anchor in the [/about](https://cchits.net/about) page should be changed to [/about#voteadj](https://cchits.net/about#voteadj)

Personally, I favour the first one.

**Comment by ymauray** [comment]
Agreed. 1st option is best

**Comment by thelovebug** [comment]
Fix in `/TEMPLATES/Source/track_detail.tpl`
