### ISSUE TITLE
Error in the PHP Log (SQL Error)

### ISSUE THREAD

**Issue by JonTheNiceGuy** [CCHits/Website#96]
[13-Sep-2018 00:32:28 America/Los_Angeles] Error creating: SQL Error: Array
(
    [sql] => INSERT INTO users (strOpenID, strCookieID, strEMail, sha1Pass, isAuthorized, isUploader, isAdmin, datLastSeen) VALUES (:strOpenID, :strCookieID, :strEMail, :sha1Pass, :isAuthorized, :isUploader, :isAdmin, :datLastSeen)
    [values] => Array
        (
            [strOpenID] =>
            [strCookieID] => <REDACTED>
            [strEMail] =>
            [sha1Pass] =>
            [isAuthorized] => 0
            [isUploader] => 0
            [isAdmin] => 0
            [datLastSeen] =>
        )

    [error] => Array
        (
            [0] => 23000
            [1] => 1048
            [2] => Column 'datLastSeen' cannot be null
        )

)

**Comment by ymauray** [comment]
I think #101 fixed that.
